---
language: python
python: "3.6"
sudo: required
services:
  - docker

install:
  - pip install -r requirements.txt
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook -c local -i tests/inventory tests/test.yml
  - ls tests/webgoat/webgoat.jar
  - ls tests/webgoat/webwolf.jar 
  - tests/webgoat/stopgoat.sh
  - ansible-playbook -c local -i tests/inventory -e "webgoat_installtype=docker" tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
