---
language: python
python: "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install -r requirements.txt
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook -c local -i tests/inventory tests/test.yml
  - ls tests/webgoat/webgoat.jar
  - ls tests/webgoat/webwolf.jar 
  - tests/webgoat/stopgoat.sh
  - ansible-playbook -c local -i tests/inventory -e "webgoat_installtype=docker" tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
