---
services:
- docker
language: python
python: "3.8"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  - pip install docker 

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook -c local -i tests/inventory tests/test.yml
  - ls tests/webgoat/webgoat.jar
  - ls tests/webgoat/webwolf.jar 
  - tests/webgoat/stopgoat.sh
  - ansible-playbook -c local -i tests/inventory -e "webgoat_installtype=docker" tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
