---
# tasks file for webgoat via docker
- name: Start WebGoat as docker
  docker_container:
    name: webgoat
    image: webgoat/goatandwolf:v{{ webgoat_version }}
    state: started
    ports:
      - "{{ webgoat_port }}:8080"
      - "{{ webwolf_port }}:9090"
    env:
      TZ: "{{ webgoat_timezone }}"
