---
# tasks file for webgoat via docker
- name: Start WebGoat as docker
  docker_container:
    name: webgoat
    image: webgoat/goatandwolf
    state: started
    ports:
      - "8080:8080"
      - "9090:9090"
    env:
      TZ: "Europe/Amsterdam"
