---
# tasks file for webgoat
- name: Create basedir for webgoat
  file:
    path: "{{ webgoat_basedir }}"
    state: directory
    mode: "0775"
  tags:
     - native
- name: Download  webgoat jar
  get_url:
    url: "https://github.com/WebGoat/WebGoat/releases/download/v{{ webgoat_version }}/webgoat-server-{{ webgoat_version }}.jar"
    checksum: "{{ webgoat_hash }}"
    dest: "{{ webgoat_basedir }}/webgoat.jar"
    mode: "0755"
  tags:
     - native
- name: Download  webwolf jar
  get_url:
    url: "https://github.com/WebGoat/WebGoat/releases/download/v{{ webgoat_version }}/webwolf-{{ webgoat_version }}.jar"
    checksum: "{{ webwolf_hash }}"
    dest: "{{ webgoat_basedir }}/webwolf.jar"
    mode: " 0755"
  tags:
     - native
- name: kill all running webgoat.jar
  shell:  pkill -9 -f webgoat.jar
  ignore_errors: true
- name: start webgoat.jar
  shell: "cd {{ webgoat_basedir }} ; nohup java -jar webgoat.jar > webgoat.log &"
  tags:
    - native
- name: wait 30 sec for port 8080
  shell: bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/localhost/8080; do sleep 1; done' & sleep 30; (kill $! || true)
  ignore_errors: true
  tags:
    - native
- name: wait 3 sec for port 9001
  shell: bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/localhost/9001; do sleep 1; done' & sleep 3; (kill $! || true)
  ignore_errors: true
  tags:
    - native
- name: start webwolf.jar
  shell: "cd {{ webgoat_basedir }} ; nohup java -jar webwolf.jar > webwolf.log &"
  tags:
    - native
